[package]
name = "pandalang-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.2", features = ["derive"] }
pandalang-repl = { path = "../repl" }
pandalang-eval = { path = "../eval" }
pandalang-parser = { path = "../parser" }
pandalang-types = { path = "../types" }