[package]
name = "pandalang-repl"
version = "0.1.0"
edition = "2021"

[dependencies]
rustyline = "10.0.0"
lazy_static = "1.4.0"
pandalang-parser = { path = "../parser" }
pandalang-eval = { path = "../eval" }
pandalang-types = { path = "../types" }