name: Deploy Playground

on:
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
    - name: npm ci
      working-directory: ./playground
      run: nix develop --command npm ci
    - name: Build
      working-directory: ./playground
      # Note that we specify the base path when deploying to Pages
      run: nix develop --command npm run build -- --base=/pandalang/
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload dist repository
        path: './playground/dist'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1

